### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [Muirey03/SilentAir#2]
.

**Comment by Nano0k** [comment]
Yep share sheet goes blank after a second. Suspect when an airdrop person pops up

**Comment by clspeter** [comment]
Same here.
Happend on my iPhone X & iPhone 6s, both is 11.3.1

**Comment by coasterracheal** [comment]
Same here! It took me a while to figure out which tweak was the culprit.
iPhone 7 Plus, iOS 11.3.1

**Comment by jaxon0523** [comment]
Its both same in iPX ios 11.3.1
